### ISSUE TITLE
UI upload fails, missing libzbar0 package

### ISSUE THREAD

**Issue by mph88** [linuxserver/docker-paperless-ngx#10]
---
name: Bug report
about: Create a report to help us improve

---
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
UI upload should work

## Current Behavior
UI upload fails

## Solution
Missing libzbar0 package. Running 

> apt install libzbar0

solves the issue.

## Steps to Reproduce

Fresh install.

## Environment
**OS:** Ubuntu 21.10
**CPU architecture:** amd64
**How docker service was installed:** Installed from official docker repo

## Command used to create docker container (run/create/compose/screenshot)
Copied compose text from dockerhub and ran from Portainer stacks.

## Docker logs
Process Process-1:1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/pydoc.py", line 347, in safeimport
    module = __import__(path)
  File "/app/paperless/src/documents/tasks.py", line 25, in <module>
    from pyzbar import pyzbar
  File "/usr/local/lib/python3.8/dist-packages/pyzbar/pyzbar.py", line 7, in <module>
    from .wrapper import (
  File "/usr/local/lib/python3.8/dist-packages/pyzbar/wrapper.py", line 151, in <module>
    zbar_version = zbar_function(
  File "/usr/local/lib/python3.8/dist-packages/pyzbar/wrapper.py", line 148, in zbar_function
    return prototype((fname, load_libzbar()))
  File "/usr/local/lib/python3.8/dist-packages/pyzbar/wrapper.py", line 127, in load_libzbar
    libzbar, dependencies = zbar_library.load()
  File "/usr/local/lib/python3.8/dist-packages/pyzbar/zbar_library.py", line 65, in load
    raise ImportError('Unable to find zbar shared library')
ImportError: Unable to find zbar shared library
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django_q/cluster.py", line 424, in worker
    f = pydoc.locate(f)
  File "/usr/lib/python3.8/pydoc.py", line 1632, in locate
    nextmodule = safeimport('.'.join(parts[:n+1]), forceload)
  File "/usr/lib/python3.8/pydoc.py", line 362, in safeimport
    raise ErrorDuringImport(path, sys.exc_info())
pydoc.ErrorDuringImport: problem in documents.tasks - ImportError: Unable to find zbar shared library

**Comment by cristiangauma** [comment]
Also, there is a bug already closed on the official project repository:

https://github.com/paperless-ngx/paperless-ngx/issues/730

**Comment by shamoon** [comment]
Its not really a bug, just a new core requirement, as noted in that issue =)

**Comment by cristiangauma** [comment]
Yep, I've just installed the packages documented on the issue and it worked. The packages are: `libzbar0` and `poppler-utils` (tested on amd64, I guess they also exist on aarch64 and armhf, but cannot test it)

**Comment by itsMaxC** [comment]
> Its not really a bug, just a new core requirement, as noted in that issue =)

Yes, but those should be included in the (upstream) Dockerfile.  There is no reason I'd need to exec into the container every time it restarts to install a dependency, that's the whole point of the Docker package.

**Comment by shamoon** [comment]
Our project Dockerfile uses a "base image" which does (or at least should) contain that dep
`FROM ghcr.io/paperless-ngx/builder/ngx-base:1.7.0 as main-app`

**Comment by darkmattercoder** [comment]
@thehedgefrog @mph88 are you aware that this very image here is a different project than the dockerfile provided by the paperless-ngx organization? 

Apparently the linuxserver image did not contain those dependencies yet. I gave those a try in #11
