### ISSUE TITLE
ARMv7 - libxslt.so.1: cannot open shared object file

### ISSUE THREAD

**Issue by rynr** [linuxserver/docker-paperless-ngx#12]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Import PDFs via Drag&Drop when running on a Rhaspberry Pi ARMv7.

## Current Behavior

Import fails without an error message.  

## Steps to Reproduce

1. Run docker-paperless-ngx on a Rhaspberry Pi ARMv7 like described on [docker hub](https://hub.docker.com/r/linuxserver/paperless-ngx).
2. Wait for paperless-ngx to start.
3. Access http://localhost:8000/
4. Login using admin/admin
5. Try to upload a pdf with drag&drop.
6. Checkout the logs.

## Environment
**OS:** Linux / Debian
**CPU architecture:** ARMv7
**How docker service was installed:**

 - Loaded [docker pgp-key](https://download.docker.com/linux/debian/gpg)
 - Added [docker apt repository](https://download.docker.com/linux/debian)
 - Installed package `docker-ce` using debian system-tools.

## Command used to create docker container (run/create/compose/screenshot)

I started it via ansible. The task is:
```yml
- name: Create paperless-ng container
  community.docker.docker_container:
    name: paperless-ng
    image: linuxserver/paperless-ngx:1.7.0
    restart_policy: unless-stopped
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: UTC
    volumes:
      - paperless-ngx-config:/config
      - paperless-ngx-data:/data
    container_default_behavior: compatibility
```

## Docker logs

```
Process Process-1:9:
Traceback (most recent call last):
  File "/usr/lib/python3.8/pydoc.py", line 347, in safeimport
    module = __import__(path)
  File "/app/paperless/src/documents/tasks.py", line 24, in <module>
    from pikepdf import Pdf
  File "/usr/local/lib/python3.8/dist-packages/pikepdf/__init__.py", line 55, in <module>
    from .models import (
  File "/usr/local/lib/python3.8/dist-packages/pikepdf/models/__init__.py", line 20, in <module>
    from .metadata import PdfMetadata
  File "/usr/local/lib/python3.8/dist-packages/pikepdf/models/metadata.py", line 29, in <module>
    from lxml import etree
ImportError: libxslt.so.1: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django_q/cluster.py", line 424, in worker
    f = pydoc.locate(f)
  File "/usr/lib/python3.8/pydoc.py", line 1632, in locate
    nextmodule = safeimport('.'.join(parts[:n+1]), forceload)
  File "/usr/lib/python3.8/pydoc.py", line 362, in safeimport
    raise ErrorDuringImport(path, sys.exc_info())
pydoc.ErrorDuringImport: problem in documents.tasks - ImportError: libxslt.so.1: cannot open shared object file: No such file or directory
16:23:55 [Q] ERROR reincarnated worker Process-1:9 after death
```

**Comment by rynr** [comment]
I installed `libxslt1.1` in the container and now it worked.  
I will create a pull-request.
