### ISSUE TITLE
`libqpdf.so.28: cannot open shared object file: No such file or directory` when importing a document

### ISSUE THREAD

**Issue by fdw** [linuxserver/docker-paperless-ngx#22]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

When uploading a document, this error turns up:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pikepdf/__init__.py", line 13, in <module>
    from . import _qpdf
ImportError: libqpdf.so.28: cannot open shared object file: No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/pydoc.py", line 347, in safeimport
    module = __import__(path)
  File "/app/paperless/src/documents/tasks.py", line 24, in <module>
    from pikepdf import Pdf
  File "/usr/local/lib/python3.8/dist-packages/pikepdf/__init__.py", line 16, in <module>
    raise ImportError(_msg) from _e
ImportError: pikepdf's extension library failed to import
```
------------------------------

## Expected Behavior

The document can be imported without problems.

## Current Behavior

When uploading a document, the UI hangs. In the logs, I can find the above error.

## Steps to Reproduce

1. Upload a document
2. Wait
3. Read logs
4. Find error

## Environment
**OS:** Manjaro
**CPU architecture:** arm64
**How docker service was installed:** From distro repo

## Command used to create docker container (run/create/compose/screenshot)

`docker create -e DOCKER_MODS=linuxserver/mods:papermerge-multilangocr -e OCRLANG="deu,eng" linuxserver/paperless-ngx`

## Docker logs

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pikepdf/__init__.py", line 13, in <module>
    from . import _qpdf
ImportError: libqpdf.so.28: cannot open shared object file: No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/pydoc.py", line 347, in safeimport
    module = __import__(path)
  File "/app/paperless/src/documents/tasks.py", line 24, in <module>
    from pikepdf import Pdf
  File "/usr/local/lib/python3.8/dist-packages/pikepdf/__init__.py", line 16, in <module>
    raise ImportError(_msg) from _e
ImportError: pikepdf's extension library failed to import
```

**Comment by aptalca** [comment]
@fdw can you test this dev image? `lspipepr/paperless-ngx:v1.7.1-pkg-c0c7f7f0-pr-23` Once you confirm it's working, we'll merge #23 
Thanks

**Comment by NTL-Remi** [comment]
I have the same problem, the dev image seems to fix it for me.

Probably irrelevant piece of information now, but my traceback had one more layer than @fdw:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pikepdf/__init__.py", line 13, in <module>
    from . import _qpdf
ImportError: libqpdf.so.28: cannot open shared object file: No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/pydoc.py", line 347, in safeimport
    module = __import__(path)
  File "/app/paperless/src/documents/tasks.py", line 24, in <module>
    from pikepdf import Pdf
  File "/usr/local/lib/python3.8/dist-packages/pikepdf/__init__.py", line 16, in <module>
    raise ImportError(_msg) from _e
ImportError: pikepdf's extension library failed to import

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django_q/cluster.py", line 424, in worker
    f = pydoc.locate(f)
  File "/usr/lib/python3.8/pydoc.py", line 1632, in locate
    nextmodule = safeimport('.'.join(parts[:n+1]), forceload)
  File "/usr/lib/python3.8/pydoc.py", line 362, in safeimport
    raise ErrorDuringImport(path, sys.exc_info())
pydoc.ErrorDuringImport: problem in documents.tasks - ImportError: pikepdf's extension library failed to import
```

**Comment by aptalca** [comment]
Thanks for the confirmation. The secondary failure also seems to be related to the pikepdf issue.

**Comment by fdw** [comment]
Sorry, I only now managed to test it, but it works fine. Thank you 🙂
