### ISSUE TITLE
TypeError: shutdown() got an unexpected keyword argument 'cancel_futures'

### ISSUE THREAD

**Issue by bdoppels** [linuxserver/docker-paperless-ngx#24]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

I try to upload a simple pdf file via the gui and i get the an error message. I already tried installing afterwards some packages that could be neccessary, from similar issues, but it didn't fix it for me.
I'm working with portainer on a raspberry pi 4. The error message i get:

![grafik](https://user-images.githubusercontent.com/15686981/170891260-239bab02-9c29-4953-94bc-52823c4f35a0.png)

------------------------------

## Expected Behavior
Upload a file without issues

## Current Behavior
Upload a file with issues

## Steps to Reproduce

1. upload a pdf
2. get the error message

## Environment
**OS:** openmediavault
**CPU architecture:** ARMv8
**How docker service was installed:** via openmediavault package management, portainer aswell

## Command used to create docker container (run/create/compose/screenshot)

```
version: "2.1"
services:
  paperless-ngx:
    image: lscr.io/linuxserver/paperless-ngx:latest
    container_name: paperless
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - /appdata/paperless:/config
      - /srv/dev-disk-by-uuid-34797fac-e6fb-410c-b5f9-bf6ac6a50b9e/paperless:/data
    ports:
      - 8001:8000
    restart: unless-stopped
```
## Docker logs

```
[2022-05-29 20:54:39,365] [INFO] [paperless.management.consumer] Using inotify to watch directory for changes: /data/consume

[2022-05-29 20:55:05,878] [INFO] [paperless.consumer] Consuming kfz.pdf

[2022-05-29 20:55:05,882] [DEBUG] [paperless.consumer] Detected mime type: application/pdf

[2022-05-29 20:55:05,890] [DEBUG] [paperless.consumer] Parser: RasterisedDocumentParser

[2022-05-29 20:55:05,898] [DEBUG] [paperless.consumer] Parsing kfz.pdf...

[2022-05-29 20:55:11,091] [INFO] [paperless.sanity_checker] Sanity checker detected no issues.

[2022-05-29 20:55:11,496] [DEBUG] [paperless.parsing.tesseract] Extracted text from PDF file /tmp/paperless/paperless-upload-m25o3eqb

[2022-05-29 20:55:11,659] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args: {'input_file': '/tmp/paperless/paperless-upload-m25o3eqb', 'output_file': '/tmp/paperless/paperless-w60t_auu/archive.pdf', 'use_threads': True, 'jobs': 2, 'language': 'eng', 'output_type': 'pdfa', 'progress_bar': False, 'skip_text': True, 'clean': True, 'deskew': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'sidecar': '/tmp/paperless/paperless-w60t_auu/sidecar.txt'}

[2022-05-29 20:55:15,716] [DEBUG] [paperless.parsing.tesseract] Deleting directory /tmp/paperless/paperless-w60t_auu

[2022-05-29 20:55:15,728] [ERROR] [paperless.consumer] Error while consuming document kfz.pdf: TypeError: shutdown() got an unexpected keyword argument 'cancel_futures'

Traceback (most recent call last):

  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run

    result = self.fn(*self.args, **self.kwargs)

  File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/pdfinfo/info.py", line 638, in _pdf_pageinfo_sync

    page = PageInfo(pdf, pageno, infile, check_pages, detailed_analysis)

  File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/pdfinfo/info.py", line 716, in __init__

    self._gather_pageinfo(pdf, pageno, infile, check_pages, detailed_analysis)

  File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/pdfinfo/info.py", line 762, in _gather_pageinfo

    for ci in _process_content_streams(

  File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/pdfinfo/info.py", line 565, in _process_content_streams

    yield from _find_regular_images(container, contentsinfo)

  File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/pdfinfo/info.py", line 483, in _find_regular_images

    yield ImageInfo(name=draw.name, pdfimage=pdfimage, shorthand=draw.shorthand)

  File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/pdfinfo/info.py", line 353, in __init__

    pim_icc = pim.icc

  File "/usr/local/lib/python3.8/dist-packages/pikepdf/models/image.py", line 479, in icc

    self._icc = ImageCms.ImageCmsProfile(iccbytesio)

  File "/usr/local/lib/python3.8/dist-packages/PIL/ImageCms.py", line 202, in __init__

    self._set(core.profile_frombytes(profile.read()))

  File "/usr/local/lib/python3.8/dist-packages/PIL/_util.py", line 19, in __getattr__

    raise self.ex

  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run

    result = self.fn(*self.args, **self.kwargs)

  File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/pdfinfo/info.py", line 638, in _pdf_pageinfo_sync

    page = PageInfo(pdf, pageno, infile, check_pages, detailed_analysis)

  File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/pdfinfo/info.py", line 716, in __init__

    self._gather_pageinfo(pdf, pageno, infile, check_pages, detailed_analysis)

  File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/pdfinfo/info.py", line 762, in _gather_pageinfo

    for ci in _process_content_streams(

  File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/pdfinfo/info.py", line 565, in _process_content_streams

    yield from _find_regular_images(container, contentsinfo)

  File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/pdfinfo/info.py", line 483, in _find_regular_images

    yield ImageInfo(name=draw.name, pdfimage=pdfimage, shorthand=draw.shorthand)

  File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/pdfinfo/info.py", line 353, in __init__

    pim_icc = pim.icc

  File "/usr/local/lib/python3.8/dist-packages/pikepdf/models/image.py", line 479, in icc

    self._icc = ImageCms.ImageCmsProfile(iccbytesio)

  File "/usr/local/lib/python3.8/dist-packages/PIL/ImageCms.py", line 202, in __init__

    self._set(core.profile_frombytes(profile.read()))

  File "/usr/local/lib/python3.8/dist-packages/PIL/_util.py", line 19, in __getattr__

    raise self.ex

  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run

    result = self.fn(*self.args, **self.kwargs)

  File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/pdfinfo/info.py", line 638, in _pdf_pageinfo_sync

    page = PageInfo(pdf, pageno, infile, check_pages, detailed_analysis)

  File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/pdfinfo/info.py", line 716, in __init__

    self._gather_pageinfo(pdf, pageno, infile, check_pages, detailed_analysis)

  File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/pdfinfo/info.py", line 762, in _gather_pageinfo

    for ci in _process_content_streams(

  File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/pdfinfo/info.py", line 565, in _process_content_streams

    yield from _find_regular_images(container, contentsinfo)

  File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/pdfinfo/info.py", line 483, in _find_regular_images

    yield ImageInfo(name=draw.name, pdfimage=pdfimage, shorthand=draw.shorthand)

  File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/pdfinfo/info.py", line 353, in __init__

    pim_icc = pim.icc

  File "/usr/local/lib/python3.8/dist-packages/pikepdf/models/image.py", line 479, in icc

    self._icc = ImageCms.ImageCmsProfile(iccbytesio)

  File "/usr/local/lib/python3.8/dist-packages/PIL/ImageCms.py", line 202, in __init__

    self._set(core.profile_frombytes(profile.read()))

  File "/usr/local/lib/python3.8/dist-packages/PIL/_util.py", line 19, in __getattr__

    raise self.ex

  File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/builtin_plugins/concurrency.py", line 135, in _execute

    result = future.result()

  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 437, in result

    return self.__get_result()

  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result

    raise self._exception

  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run

    result = self.fn(*self.args, **self.kwargs)

  File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/pdfinfo/info.py", line 638, in _pdf_pageinfo_sync

    page = PageInfo(pdf, pageno, infile, check_pages, detailed_analysis)

  File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/pdfinfo/info.py", line 716, in __init__

    self._gather_pageinfo(pdf, pageno, infile, check_pages, detailed_analysis)

  File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/pdfinfo/info.py", line 762, in _gather_pageinfo

    for ci in _process_content_streams(

  File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/pdfinfo/info.py", line 565, in _process_content_streams

    yield from _find_regular_images(container, contentsinfo)

  File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/pdfinfo/info.py", line 483, in _find_regular_images

    yield ImageInfo(name=draw.name, pdfimage=pdfimage, shorthand=draw.shorthand)

  File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/pdfinfo/info.py", line 353, in __init__

    pim_icc = pim.icc

  File "/usr/local/lib/python3.8/dist-packages/pikepdf/models/image.py", line 479, in icc

    self._icc = ImageCms.ImageCmsProfile(iccbytesio)

  File "/usr/local/lib/python3.8/dist-packages/PIL/ImageCms.py", line 202, in __init__

    self._set(core.profile_frombytes(profile.read()))

  File "/usr/local/lib/python3.8/dist-packages/PIL/_util.py", line 19, in __getattr__

    raise self.ex

  File "/usr/local/lib/python3.8/dist-packages/PIL/ImageCms.py", line 25, in <module>

    from PIL import _imagingcms

ImportError: cannot import name '_imagingcms' from 'PIL' (/usr/local/lib/python3.8/dist-packages/PIL/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/app/paperless/src/paperless_tesseract/parsers.py", line 261, in parse

    ocrmypdf.ocr(**args)

  File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/api.py", line 337, in ocr

    return run_pipeline(options=options, plugin_manager=plugin_manager, api=True)

  File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/_sync.py", line 370, in run_pipeline

    pdfinfo = get_pdfinfo(

  File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/_pipeline.py", line 163, in get_pdfinfo

    return PdfInfo(

  File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/pdfinfo/info.py", line 904, in __init__

    self._pages = _pdf_pageinfo_concurrent(

  File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/pdfinfo/info.py", line 681, in _pdf_pageinfo_concurrent

    executor(

  File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/_concurrent.py", line 82, in __call__

    self._execute(

  File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/builtin_plugins/concurrency.py", line 148, in _execute

    executor.shutdown(wait=False, cancel_futures=True)

TypeError: shutdown() got an unexpected keyword argument 'cancel_futures'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/app/paperless/src/documents/consumer.py", line 261, in try_consume_file

    document_parser.parse(self.path, mime_type, self.filename)

  File "/app/paperless/src/paperless_tesseract/parsers.py", line 314, in parse

    raise ParseError(f"{e.__class__.__name__}: {str(e)}")

documents.parsers.ParseError: TypeError: shutdown() got an unexpected keyword argument 'cancel_futures'
```

**Comment by bdoppels** [comment]
i found out, that other pdf file were working. After some research I found out that after I converted the failured pdf file in a PDF/X the upload was successfull.

**Comment by wrobbler** [comment]
I am having the same issue when uploading a pdf and I get the same error message.

Expected Behavior
PDF upload is working

Current Behavior
PDF upload is failing during processing

Steps to Reproduce
Upload a PDF via GUI

Environment
OS: Raspbian GNU/Linux 10 (buster)
CPU architecture: ARM

docker-compose.yml
```
version: "3"
services:
  paperless-ngx:
    image: linuxserver/paperless-ngx:latest
    container_name: paperless-ngx
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - PAPERLESS_URL=${PAPERLESS_URL}
    volumes:
      - /media/datadrive/paperless/config:/config
      - /media/datadrive/paperless/data:/data
    restart: unless-stopped
```

Docker logs

```
paperless-ngx    | 14:58:52 [Q] INFO Process-1:6 processing [myfile.pdf]
paperless-ngx    | [2022-07-04 14:58:52,811] [INFO] [paperless.consumer] Consuming myfile.pdf
paperless-ngx    | [2022-07-04 14:58:54,071] [ERROR] [paperless.consumer] Error while consuming document myfile.pdf: TypeError: shutdown() got an unexpected keyword argument 'cancel_futures'
paperless-ngx    | Traceback (most recent call last):
paperless-ngx    |   File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/builtin_plugins/concurrency.py", line 135, in _execute
paperless-ngx    |     result = future.result()
paperless-ngx    |   File "/usr/lib/python3.8/concurrent/futures/_base.py", line 437, in result
paperless-ngx    |     return self.__get_result()
paperless-ngx    |   File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
paperless-ngx    |     raise self._exception
paperless-ngx    |   File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
paperless-ngx    |     result = self.fn(*self.args, **self.kwargs)
paperless-ngx    |   File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/pdfinfo/info.py", line 638, in _pdf_pageinfo_sync
paperless-ngx    |     page = PageInfo(pdf, pageno, infile, check_pages, detailed_analysis)
paperless-ngx    |   File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/pdfinfo/info.py", line 716, in __init__
paperless-ngx    |     self._gather_pageinfo(pdf, pageno, infile, check_pages, detailed_analysis)
paperless-ngx    |   File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/pdfinfo/info.py", line 762, in _gather_pageinfo
paperless-ngx    |     for ci in _process_content_streams(
paperless-ngx    |   File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/pdfinfo/info.py", line 566, in _process_content_streams
paperless-ngx    |     yield from _find_form_xobject_images(pdf, container, contentsinfo)
paperless-ngx    |   File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/pdfinfo/info.py", line 513, in _find_form_xobject_images
paperless-ngx    |     yield from _process_content_streams(
paperless-ngx    |   File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/pdfinfo/info.py", line 565, in _process_content_streams
paperless-ngx    |     yield from _find_regular_images(container, contentsinfo)
paperless-ngx    |   File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/pdfinfo/info.py", line 483, in _find_regular_images
paperless-ngx    |     yield ImageInfo(name=draw.name, pdfimage=pdfimage, shorthand=draw.shorthand)
paperless-ngx    |   File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/pdfinfo/info.py", line 353, in __init__
paperless-ngx    |     pim_icc = pim.icc
paperless-ngx    |   File "/usr/local/lib/python3.8/dist-packages/pikepdf/models/image.py", line 479, in icc
paperless-ngx    |     self._icc = ImageCms.ImageCmsProfile(iccbytesio)
paperless-ngx    |   File "/usr/local/lib/python3.8/dist-packages/PIL/ImageCms.py", line 202, in __init__
paperless-ngx    |     self._set(core.profile_frombytes(profile.read()))
paperless-ngx    |   File "/usr/local/lib/python3.8/dist-packages/PIL/_util.py", line 19, in __getattr__
paperless-ngx    |     raise self.ex
paperless-ngx    |   File "/usr/local/lib/python3.8/dist-packages/PIL/ImageCms.py", line 25, in <module>
paperless-ngx    |     from PIL import _imagingcms
paperless-ngx    | ImportError: cannot import name '_imagingcms' from 'PIL' (/usr/local/lib/python3.8/dist-packages/PIL/__init__.py)
paperless-ngx    |
paperless-ngx    | During handling of the above exception, another exception occurred:
paperless-ngx    |
paperless-ngx    | Traceback (most recent call last):
paperless-ngx    |   File "/app/paperless/src/paperless_tesseract/parsers.py", line 261, in parse
paperless-ngx    |     ocrmypdf.ocr(**args)
paperless-ngx    |   File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/api.py", line 337, in ocr
paperless-ngx    |     return run_pipeline(options=options, plugin_manager=plugin_manager, api=True)
paperless-ngx    |   File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/_sync.py", line 370, in run_pipeline
paperless-ngx    |     pdfinfo = get_pdfinfo(
paperless-ngx    |   File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/_pipeline.py", line 163, in get_pdfinfo
paperless-ngx    |     return PdfInfo(
paperless-ngx    |   File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/pdfinfo/info.py", line 904, in __init__
paperless-ngx    |     self._pages = _pdf_pageinfo_concurrent(
paperless-ngx    |   File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/pdfinfo/info.py", line 681, in _pdf_pageinfo_concurrent
paperless-ngx    |     executor(
paperless-ngx    |   File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/_concurrent.py", line 82, in __call__
paperless-ngx    |     self._execute(
paperless-ngx    |   File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/builtin_plugins/concurrency.py", line 148, in _execute
paperless-ngx    |     executor.shutdown(wait=False, cancel_futures=True)
paperless-ngx    | TypeError: shutdown() got an unexpected keyword argument 'cancel_futures'
paperless-ngx    |
paperless-ngx    | During handling of the above exception, another exception occurred:
paperless-ngx    |
paperless-ngx    | Traceback (most recent call last):
paperless-ngx    |   File "/app/paperless/src/documents/consumer.py", line 261, in try_consume_file
paperless-ngx    |     document_parser.parse(self.path, mime_type, self.filename)
paperless-ngx    |   File "/app/paperless/src/paperless_tesseract/parsers.py", line 314, in parse
paperless-ngx    |     raise ParseError(f"{e.__class__.__name__}: {str(e)}")
paperless-ngx    | documents.parsers.ParseError: TypeError: shutdown() got an unexpected keyword argument 'cancel_futures'
paperless-ngx    | 14:58:54 [Q] INFO Process-1:6 stopped doing work
paperless-ngx    | 14:58:54 [Q] ERROR Failed [myfile.pdf] - myfile.pdf: Error while consuming document myfile.pdf: TypeError: shutdown() got an unexpected keyword argument 'cancel_futures' : Traceback (most recent call last):
paperless-ngx    |   File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/builtin_plugins/concurrency.py", line 135, in _execute
paperless-ngx    |     result = future.result()
paperless-ngx    |   File "/usr/lib/python3.8/concurrent/futures/_base.py", line 437, in result
paperless-ngx    |     return self.__get_result()
paperless-ngx    |   File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
paperless-ngx    |     raise self._exception
paperless-ngx    |   File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
paperless-ngx    |     result = self.fn(*self.args, **self.kwargs)
paperless-ngx    |   File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/pdfinfo/info.py", line 638, in _pdf_pageinfo_sync
paperless-ngx    |     page = PageInfo(pdf, pageno, infile, check_pages, detailed_analysis)
paperless-ngx    |   File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/pdfinfo/info.py", line 716, in __init__
paperless-ngx    |     self._gather_pageinfo(pdf, pageno, infile, check_pages, detailed_analysis)
paperless-ngx    |   File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/pdfinfo/info.py", line 762, in _gather_pageinfo
paperless-ngx    |     for ci in _process_content_streams(
paperless-ngx    |   File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/pdfinfo/info.py", line 566, in _process_content_streams
paperless-ngx    |     yield from _find_form_xobject_images(pdf, container, contentsinfo)
paperless-ngx    |   File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/pdfinfo/info.py", line 513, in _find_form_xobject_images
paperless-ngx    |     yield from _process_content_streams(
paperless-ngx    |   File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/pdfinfo/info.py", line 565, in _process_content_streams
paperless-ngx    |     yield from _find_regular_images(container, contentsinfo)
paperless-ngx    |   File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/pdfinfo/info.py", line 483, in _find_regular_images
paperless-ngx    |     yield ImageInfo(name=draw.name, pdfimage=pdfimage, shorthand=draw.shorthand)
paperless-ngx    |   File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/pdfinfo/info.py", line 353, in __init__
paperless-ngx    |     pim_icc = pim.icc
paperless-ngx    |   File "/usr/local/lib/python3.8/dist-packages/pikepdf/models/image.py", line 479, in icc
paperless-ngx    |     self._icc = ImageCms.ImageCmsProfile(iccbytesio)
paperless-ngx    |   File "/usr/local/lib/python3.8/dist-packages/PIL/ImageCms.py", line 202, in __init__
paperless-ngx    |     self._set(core.profile_frombytes(profile.read()))
paperless-ngx    |   File "/usr/local/lib/python3.8/dist-packages/PIL/_util.py", line 19, in __getattr__
paperless-ngx    |     raise self.ex
paperless-ngx    |   File "/usr/local/lib/python3.8/dist-packages/PIL/ImageCms.py", line 25, in <module>
paperless-ngx    |     from PIL import _imagingcms
paperless-ngx    | ImportError: cannot import name '_imagingcms' from 'PIL' (/usr/local/lib/python3.8/dist-packages/PIL/__init__.py)
paperless-ngx    |
paperless-ngx    | During handling of the above exception, another exception occurred:
paperless-ngx    |
paperless-ngx    | Traceback (most recent call last):
paperless-ngx    |   File "/app/paperless/src/paperless_tesseract/parsers.py", line 261, in parse
paperless-ngx    |     ocrmypdf.ocr(**args)
paperless-ngx    |   File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/api.py", line 337, in ocr
paperless-ngx    |     return run_pipeline(options=options, plugin_manager=plugin_manager, api=True)
paperless-ngx    |   File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/_sync.py", line 370, in run_pipeline
paperless-ngx    |     pdfinfo = get_pdfinfo(
paperless-ngx    |   File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/_pipeline.py", line 163, in get_pdfinfo
paperless-ngx    |     return PdfInfo(
paperless-ngx    |   File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/pdfinfo/info.py", line 904, in __init__
paperless-ngx    |     self._pages = _pdf_pageinfo_concurrent(
paperless-ngx    |   File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/pdfinfo/info.py", line 681, in _pdf_pageinfo_concurrent
paperless-ngx    |     executor(
paperless-ngx    |   File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/_concurrent.py", line 82, in __call__
paperless-ngx    |     self._execute(
paperless-ngx    |   File "/usr/local/lib/python3.8/dist-packages/ocrmypdf/builtin_plugins/concurrency.py", line 148, in _execute
paperless-ngx    |     executor.shutdown(wait=False, cancel_futures=True)
paperless-ngx    | TypeError: shutdown() got an unexpected keyword argument 'cancel_futures'
paperless-ngx    |
paperless-ngx    | During handling of the above exception, another exception occurred:
paperless-ngx    |
paperless-ngx    | Traceback (most recent call last):
paperless-ngx    |   File "/usr/local/lib/python3.8/dist-packages/asgiref/sync.py", line 275, in main_wrap
paperless-ngx    |     raise exc_info[1]
paperless-ngx    |   File "/app/paperless/src/documents/consumer.py", line 261, in try_consume_file
paperless-ngx    |     document_parser.parse(self.path, mime_type, self.filename)
paperless-ngx    |   File "/app/paperless/src/paperless_tesseract/parsers.py", line 314, in parse
paperless-ngx    |     raise ParseError(f"{e.__class__.__name__}: {str(e)}")
paperless-ngx    | documents.parsers.ParseError: TypeError: shutdown() got an unexpected keyword argument 'cancel_futures'
paperless-ngx    |
paperless-ngx    | During handling of the above exception, another exception occurred:
paperless-ngx    |
paperless-ngx    | Traceback (most recent call last):
paperless-ngx    |   File "/usr/local/lib/python3.8/dist-packages/django_q/cluster.py", line 432, in worker
paperless-ngx    |     res = f(*task["args"], **task["kwargs"])
paperless-ngx    |   File "/app/paperless/src/documents/tasks.py", line 298, in consume_file
paperless-ngx    |     document = Consumer().try_consume_file(
paperless-ngx    |   File "/app/paperless/src/documents/consumer.py", line 280, in try_consume_file
paperless-ngx    |     self._fail(
paperless-ngx    |   File "/app/paperless/src/documents/consumer.py", line 81, in _fail
paperless-ngx    |     raise ConsumerError(f"{self.filename}: {log_message or message}")
paperless-ngx    | documents.consumer.ConsumerError: myfile.pdf: Error while consuming document myfile.pdf: TypeError: shutdown() got an unexpected keyword argument 'cancel_futures'
```

**Comment by wrobbler** [comment]
According to the documentation the cancel_futures argument was added in python 3.9 (https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.Executor.shutdown) but according to the logs the error is thrown when executing python 3.8
