### ISSUE TITLE
Error while processing gmail account

### ISSUE THREAD

**Issue by queen4me** [linuxserver/docker-paperless-ngx#35]
## Expected Behavior
Process mail-attachments in PDF format.

## Current Behavior
paperless.log reports: Error while processing mail account
mail.log: Error while authenticating account

## Steps to Reproduce
Every 10 minutes I get an error in the logs.

e-mail-account configured in paperless-ngx:

Name: john.doe@gmail.com
IMAP-Server: imap.gmail.com
IMAP-Port: 993
IMAP-Security: Use SSL
Username: john.doe@gmail.com
Password: *********

## Environment
**OS: Ubuntu 20.04 LTS server**
**CPU architecture:** x86_64
**How docker service was installed:**

## Command used to create docker container (run/create/compose/screenshot)
docker-compose.yml:

version: "2.1"
services:
  paperless-ngx:
    image: lscr.io/linuxserver/paperless-ngx:latest
    container_name: paperless-ngx
    volumes:
      - /home/john/docker/paperless-ngx:/config
      - /mnt/nas/paperless-ngx:/data
    env_file: docker-compose.env
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 8601:8000
    restart: unless-stopped

## Docker logs
paperless.log:

[2022-09-02 16:45:50,875] [ERROR] [paperless.mail.tasks] Error while processing mail account john.doe@gmail.com
Traceback (most recent call last):
  File "/app/paperless/src/paperless_mail/mail.py", line 180, in handle_mail_account
    M.login(account.username, account.password)
  File "/usr/local/lib/python3.8/dist-packages/imap_tools/mailbox.py", line 65, in login
    check_command_status(login_result, MailboxLoginError)
  File "/usr/local/lib/python3.8/dist-packages/imap_tools/utils.py", line 46, in check_command_status
    raise exception(command_result=command_result, expected=expected)
imap_tools.errors.MailboxLoginError: Response status "OK" expected, but "NO" received. Data: [b'[AUTHENTICATIONFAILED] Invalid credentials (Failure)']
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/app/paperless/src/paperless_mail/tasks.py", line 15, in process_mail_accounts
    total_new_documents += MailAccountHandler().handle_mail_account(account)
  File "/app/paperless/src/paperless_mail/mail.py", line 212, in handle_mail_account
    raise MailError(
paperless_mail.mail.MailError: Error while authenticating account john.doe@gmail.com

mail.log:

[2022-09-02 16:45:50,598] [DEBUG] [paperless_mail] Processing mail account john.doe@gmail.com
[2022-09-02 16:45:50,854] [ERROR] [paperless_mail] Error while authenticating account john.doe@gmail.com: Response status "OK" expected, but "NO" received. Data: [b'[AUTHENTICATIONFAILED] Invalid credentials (Failure)']

**Comment by aptalca** [comment]
It says invalid credentials

Also, if truly a bug, it should be reported upstream to paperless-ngx as it's an app feature and not docker specific

**Comment by j0nnymoe** [comment]
You have to create an app password within your Google mail account.

**Comment by queen4me** [comment]
Exactly this is what I did. I configured two gmail accounts. For the one with 2FA I generated an app password while for the other account I don't use 2FA.
Same error in the log for both accounts.

Do I have to configure anything in your container for Port 993 to be able to access gmail?

**Comment by queen4me** [comment]
> It says invalid credentials
> 
> Also, if truly a bug, it should be reported upstream to paperless-ngx as it's an app feature and not docker specific

I had the same idea but can't explain why I should be the only one with this problem.
Unfortunately I'm not a docker Pro.
